=== B-HS/TAIDE/native/taide-native-editor/resources/json-schema-draft-04.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "schemaArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#"
      }
    },
    "positiveInteger": {
      "type": "integer",
      "minimum": 0
    },
    "positiveIntegerDefault0": {
      "allOf": [
        {
          "$ref": "#/definitions/positiveInteger"
        },
        {
          "default": 0
        }
      ]
    },
    "simpleTypes": {
      "type": "string",
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "object",
        "string"
      ]
    },
    "stringArray": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uri",
      "description": "A unique identifier for the schema."
    },
    "$schema": {
      "type": "string",
      "format": "uri",
      "description": "The schema to verify this document against."
    },
    "title": {
      "type": "string",
      "description": "A descriptive title of the element."
    },
    "description": {
      "type": "string",
      "description": "A long description of the element. Used in hover menus and suggestions."
    },
    "default": {
      "description": "A default value. Used by suggestions."
    },
    "multipleOf": {
      "type": "number",
      "minimum": 0,
      "exclusiveMinimum": true,
      "description": "A number that should cleanly divide the current value (i.e. have no remainder)."
    },
    "maximum": {
      "type": "number",
      "description": "The maximum numerical value, inclusive by default."
    },
    "exclusiveMaximum": {
      "type": "boolean",
      "default": false,
      "description": "Makes the maximum property exclusive."
    },
    "minimum": {
      "type": "number",
      "description": "The minimum numerical value, inclusive by default."
    },
    "exclusiveMinimum": {
      "type": "boolean",
      "default": false,
      "description": "Makes the minimum property exclusive."
    },
    "maxLength": {
      "allOf": [
        {
          "$ref": "#/definitions/positiveInteger"
        }
      ],
      "description": "The maximum length of a string."
    },
    "minLength": {
      "allOf": [
        {
          "$ref": "#/definitions/positiveIntegerDefault0"
        }
      ],
      "description": "The minimum length of a string."
    },
    "pattern": {
      "type": "string",
      "format": "regex",
      "description": "A regular expression to match the string against. It is not implicitly anchored."
    },
    "additionalItems": {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "$ref": "#"
        }
      ],
      "default": {},
      "description": "For arrays, only when items is set as an array. If it is a schema, then this schema validates items after the ones specified by the items array. If it is false, then additional items will cause validation to fail."
    },
    "items": {
      "anyOf": [
        {
          "$ref": "#"
        },
        {
          "$ref": "#/definitions/schemaArray"
        }
      ],
      "default": {},
      "description": "For arrays. Can either be a schema to validate every element against or an array of schemas to validate each item against in order (the first schema will validate the first element, the second schema will validate the second element, and so on."
    },
    "maxItems": {
      "allOf": [
        {
          "$ref": "#/definitions/positiveInteger"
        }
      ],
      "description": "The maximum number of items that can be inside an array. Inclusive."
    },
    "minItems": {
      "allOf": [
        {
          "$ref": "#/definitions/positiveIntegerDefault0"
        }
      ],
      "description": "The minimum number of items that can be inside an array. Inclusive."
    },
    "uniqueItems": {
      "type": "boolean",
      "default": false,
      "description": "If all of the items in the array must be unique. Defaults to false."
    },
    "maxProperties": {
      "allOf": [
        {
          "$ref": "#/definitions/positiveInteger"
        }
      ],
      "description": "The maximum number of properties an object can have. Inclusive."
    },
    "minProperties": {
      "allOf": [
        {
          "$ref": "#/definitions/positiveIntegerDefault0"
        }
      ],
      "description": "The minimum number of properties an object can have. Inclusive."
    },
    "required": {
      "allOf": [
        {
          "$ref": "#/definitions/stringArray"
        }
      ],
      "description": "An array of strings that lists the names of all properties required on this object."
    },
    "additionalProperties": {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "$ref": "#"
        }
      ],
      "default": {},
      "description": "Either a schema or a boolean. If a schema, then used to validate all properties not matched by 'properties' or 'patternProperties'. If false, then any properties not matched by either will cause this schema to fail."
    },
    "definitions": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {},
      "description": "Not used for validation. Place subschemas here that you wish to reference inline with $ref."
    },
    "properties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {},
      "description": "A map of property names to schemas for each property."
    },
    "patternProperties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {},
      "description": "A map of regular expressions on property names to schemas for matching properties."
    },
    "dependencies": {
      "type": "object",
      "additionalProperties": {
        "anyOf": [
          {
            "$ref": "#"
          },
          {
            "$ref": "#/definitions/stringArray"
          }
        ]
      },
      "description": "A map of property names to either an array of property names or a schema. An array of property names means the property named in the key depends on the properties in the array being present in the object in order to be valid. If the value is a schema, then the schema is only applied to the object if the property in the key exists on the object."
    },
    "enum": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "description": "The set of literal values that are valid."
    },
    "type": {
      "anyOf": [
        {
          "$ref": "#/definitions/simpleTypes"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/simpleTypes"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      ],
      "description": "Either a string of one of the basic schema types (number, integer, null, array, object, boolean, string) or an array of strings specifying a subset of those types."
    },
    "format": {
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "date-time",
            "uri",
            "email",
            "hostname",
            "ipv4",
            "ipv6",
            "regex"
          ]
        },
        {
          "type": "string"
        }
      ],
      "description": "Describes the format expected for the value."
    },
    "allOf": {
      "allOf": [
        {
          "$ref": "#/definitions/schemaArray"
        }
      ],
      "description": "An array of schemas, all of which must match."
    },
    "anyOf": {
      "allOf": [
        {
          "$ref": "#/definitions/schemaArray"
        }
      ],
      "description": "An array of schemas, where at least one must match."
    },
    "oneOf": {
      "allOf": [
        {
          "$ref": "#/definitions/schemaArray"
        }
      ],
      "description": "An array of schemas, exactly one of which must match."
    },
    "not": {
      "allOf": [
        {
          "$ref": "#"
        }
      ],
      "description": "A schema which must not match."
    }
  },
  "dependencies": {
    "exclusiveMaximum": [
      "maximum"
    ],
    "exclusiveMinimum": [
      "minimum"
    ]
  },
  "default": {}
}

=== B-HS/TAIDE/native/taide-native-editor/resources/json-schema-draft-07.json
{
  "definitions": {
    "schemaArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#"
      }
    },
    "nonNegativeInteger": {
      "type": "integer",
      "minimum": 0
    },
    "nonNegativeIntegerDefault0": {
      "allOf": [
        {
          "$ref": "#/definitions/nonNegativeInteger"
        },
        {
          "default": 0
        }
      ]
    },
    "simpleTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "object",
        "string"
      ]
    },
    "stringArray": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "default": []
    }
  },
  "type": [
    "object",
    "boolean"
  ],
  "properties": {
    "$id": {
      "type": "string",
      "format": "uri-reference",
      "description": "A unique identifier for the schema."
    },
    "$schema": {
      "type": "string",
      "format": "uri",
      "description": "The schema to verify this document against."
    },
    "$ref": {
      "type": "string",
      "format": "uri-reference",
      "description": "Reference a definition hosted on any location."
    },
    "$comment": {
      "type": "string",
      "description": "Comments from schema authors to readers or maintainers of the schema."
    },
    "title": {
      "type": "string",
      "description": "A descriptive title of the element."
    },
    "description": {
      "type": "string",
      "description": "A long description of the element. Used in hover menus and suggestions."
    },
    "default": {
      "description": "A default value. Used by suggestions."
    },
    "readOnly": {
      "type": "boolean",
      "default": false,
      "description": "Indicates that the value of the instance is managed exclusively by the owning authority."
    },
    "examples": {
      "type": "array",
      "items": true,
      "description": "Sample JSON values associated with a particular schema, for the purpose of illustrating usage."
    },
    "multipleOf": {
      "type": "number",
      "exclusiveMinimum": 0,
      "description": "A number that should cleanly divide the current value (i.e. have no remainder)."
    },
    "maximum": {
      "type": "number",
      "description": "The maximum numerical value, inclusive by default."
    },
    "exclusiveMaximum": {
      "type": "number",
      "description": "Makes the maximum property exclusive."
    },
    "minimum": {
      "type": "number",
      "description": "The minimum numerical value, inclusive by default."
    },
    "exclusiveMinimum": {
      "type": "number",
      "description": "Makes the minimum property exclusive."
    },
    "maxLength": {
      "$ref": "#/definitions/nonNegativeInteger",
      "description": "The maximum length of a string."
    },
    "minLength": {
      "$ref": "#/definitions/nonNegativeIntegerDefault0",
      "description": "The minimum length of a string."
    },
    "pattern": {
      "type": "string",
      "format": "regex",
      "description": "A regular expression to match the string against. It is not implicitly anchored."
    },
    "additionalItems": {
      "$ref": "#",
      "description": "For arrays, only when items is set as an array. If it is a schema, then this schema validates items after the ones specified by the items array. If it is false, then additional items will cause validation to fail."
    },
    "items": {
      "anyOf": [
        {
          "$ref": "#"
        },
        {
          "$ref": "#/definitions/schemaArray"
        }
      ],
      "default": true,
      "description": "For arrays. Can either be a schema to validate every element against or an array of schemas to validate each item against in order (the first schema will validate the first element, the second schema will validate the second element, and so on."
    },
    "maxItems": {
      "$ref": "#/definitions/nonNegativeInteger",
      "description": "The maximum number of items that can be inside an array. Inclusive."
    },
    "minItems": {
      "$ref": "#/definitions/nonNegativeIntegerDefault0",
      "description": "The minimum number of items that can be inside an array. Inclusive."
    },
    "uniqueItems": {
      "type": "boolean",
      "default": false,
      "description": "If all of the items in the array must be unique. Defaults to false."
    },
    "contains": {
      "$ref": "#",
      "description": "An array instance is valid against \"contains\" if at least one of its elements is valid against the given schema."
    },
    "maxProperties": {
      "$ref": "#/definitions/nonNegativeInteger",
      "description": "The maximum number of properties an object can have. Inclusive."
    },
    "minProperties": {
      "$ref": "#/definitions/nonNegativeIntegerDefault0",
      "description": "The minimum number of properties an object can have. Inclusive."
    },
    "required": {
      "$ref": "#/definitions/stringArray",
      "description": "An array of strings that lists the names of all properties required on this object."
    },
    "additionalProperties": {
      "$ref": "#",
      "description": "Either a schema or a boolean. If a schema, then used to validate all properties not matched by 'properties' or 'patternProperties'. If false, then any properties not matched by either will cause this schema to fail."
    },
    "definitions": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {},
      "description": "Not used for validation. Place subschemas here that you wish to reference inline with $ref."
    },
    "properties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {},
      "description": "A map of property names to schemas for each property."
    },
    "patternProperties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "propertyNames": {
        "format": "regex"
      },
      "default": {},
      "description": "A map of regular expressions on property names to schemas for matching properties."
    },
    "dependencies": {
      "type": "object",
      "additionalProperties": {
        "anyOf": [
          {
            "$ref": "#"
          },
          {
            "$ref": "#/definitions/stringArray"
          }
        ]
      },
      "description": "A map of property names to either an array of property names or a schema. An array of property names means the property named in the key depends on the properties in the array being present in the object in order to be valid. If the value is a schema, then the schema is only applied to the object if the property in the key exists on the object."
    },
    "propertyNames": {
      "$ref": "#",
      "description": "If the instance is an object, this keyword validates if every property name in the instance validates against the provided schema."
    },
    "const": {
      "description": "An instance validates successfully against this keyword if its value is equal to the value of the keyword."
    },
    "enum": {
      "type": "array",
      "items": true,
      "minItems": 1,
      "uniqueItems": true,
      "description": "The set of literal values that are valid."
    },
    "type": {
      "anyOf": [
        {
          "$ref": "#/definitions/simpleTypes"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/simpleTypes"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      ],
      "description": "Either a string of one of the basic schema types (number, integer, null, array, object, boolean, string) or an array of strings specifying a subset of those types."
    },
    "format": {
      "type": "string",
      "description": "Describes the format expected for the value."
    },
    "contentMediaType": {
      "type": "string",
      "description": "Describes the media type of a string property."
    },
    "contentEncoding": {
      "type": "string",
      "description": "Describes the content encoding of a string property."
    },
    "if": {
      "$ref": "#",
      "description": "The validation outcome of the \"if\" subschema controls which of the \"then\" or \"else\" keywords are evaluated."
    },
    "then": {
      "$ref": "#",
      "description": "The \"if\" subschema is used for validation when the \"if\" subschema succeeds."
    },
    "else": {
      "$ref": "#",
      "description": "The \"else\" subschema is used for validation when the \"if\" subschema fails."
    },
    "allOf": {
      "$ref": "#/definitions/schemaArray",
      "description": "An array of schemas, all of which must match."
    },
    "anyOf": {
      "$ref": "#/definitions/schemaArray",
      "description": "An array of schemas, where at least one must match."
    },
    "oneOf": {
      "$ref": "#/definitions/schemaArray",
      "description": "An array of schemas, exactly one of which must match."
    },
    "not": {
      "$ref": "#",
      "description": "A schema which must not match."
    }
  },
  "default": true
}
